### ISSUE TITLE
Latest Official firmware link for RG350M is dead?

### ISSUE THREAD

**Issue by brianbianco** [retrogamehandheld/rg350m#1]
https://rg350.i0.wtf/RG350M-HDMI-20200510.IMG is issuing a 502 bad gateway right now.

**Comment by nosovae-dev** [comment]
Yeah, looks like it's dead for me 404, but I found this link https://rs97.bitgala.xyz/RG350M/ but here only stock fw

**Comment by juins1** [comment]
if anyone can get a link for the new stable hdmi firmware pls share ty

**Comment by szabotudor** [comment]
Yeah, I have the same problem, When will this get fixed?

**Comment by GreenMan36** [comment]
Should be fixed.

**Comment by macropin** [comment]
Is there a more official source for the firmware?

**Comment by GreenMan36** [comment]
@macropin 
"RG-350m Firmware (STABLE RELEASE)"
Is the stock Rom with a few stability and usability improvements.
The only "more official source" would be the firmware which your device got shipped with.
